// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() {
    driver.get("http://localhost:3000//login");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.cssSelector(".auth__container")).click();
    driver.findElement(By.id("mui-1")).click();
    driver.findElement(By.cssSelector(".auth__container")).click();
    driver.findElement(By.cssSelector(".auth__container")).click();
    driver.findElement(By.cssSelector(".auth__container")).click();
    driver.findElement(By.id("mui-1")).click();
    driver.findElement(By.id("mui-1")).sendKeys("amandalal56386@gmail.com");
    driver.findElement(By.id("mui-2")).click();
    driver.findElement(By.id("mui-2")).sendKeys("aman1234");
    driver.findElement(By.cssSelector(".MuiButtonBase-root")).click();
    driver.findElement(By.cssSelector("a:nth-child(1) > .MuiButtonBase-root")).click();
    driver.findElement(By.cssSelector("a:nth-child(2) > .MuiButtonBase-root")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("a:nth-child(3) > .MuiButtonBase-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("a:nth-child(3) > .MuiButtonBase-root")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("mui-3")).click();
    driver.findElement(By.id("mui-3")).sendKeys("test product");
    driver.findElement(By.id("mui-4")).click();
    driver.findElement(By.id("mui-4")).sendKeys("test description");
    driver.findElement(By.id("mui-5")).click();
    driver.findElement(By.id("mui-5")).sendKeys("120");
    driver.findElement(By.id("mui-6")).click();
    driver.findElement(By.id("mui-6")).sendKeys("120");
    driver.findElement(By.id("mui-7")).click();
    driver.findElement(By.id("mui-7")).sendKeys("nothing");
    driver.findElement(By.cssSelector(".MuiButton-contained")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".product__container:nth-child(5) .MuiCardMedia-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".product__container:nth-child(2) .MuiCardMedia-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".product__container:nth-child(2) .MuiCardMedia-root")).click();
    driver.findElement(By.cssSelector(".MuiButton-contained")).click();
    driver.findElement(By.linkText("Logout")).click();
  }
}
